# Generated by Django 4.1 on 2022-08-03 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.FloatField()),
                ('data_hora', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
