# Generated by Django 4.1 on 2022-08-03 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0001_initial'),
        ('conta_do_banco', '0002_alter_contabanco_num_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabanco',
            name='deposito',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='deposito.deposito'),
            preserve_default=False,
        ),
    ]
