# Generated by Django 4.1 on 2022-08-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta_do_banco', '0003_contabanco_deposito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabanco',
            name='deposito',
        ),
    ]
