# Generated by Django 4.1 on 2022-08-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_do_banco', '0005_contabanco_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabanco',
            name='saldo',
            field=models.FloatField(),
        ),
    ]
