# Generated by Django 4.1 on 2022-08-04 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferencia', models.FloatField()),
                ('data_hora', models.DateField(default=datetime.datetime)),
            ],
        ),
    ]
