# Generated by Django 4.1 on 2022-08-04 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='data_hora',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
